### ISSUE TITLE
Compilation error after Chatkit PR

### ISSUE THREAD

**Issue by jiayushe** [source-academy/cadet#414]
I am getting compilation error after merging the Chatkit PR. Is there something I missed out?
```
== Compilation error in file lib/mix/tasks/users/chat.ex ==
** (ArgumentError) could not fetch application environment :chat for application :cadet because the application was not loaded/started. If your application depends on :cadet at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
    (elixir) lib/application.ex:495: Application.fetch_env!/2
    lib/mix/tasks/users/chat.ex:24: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by geshuming** [comment]
Did you update your `secrets.exs` file. There are some new fields

**Comment by jiayushe** [comment]
Yea I forgot to update the file. Thanks for your help!
